(* open! Import *)
(**)
(* let send t (id : Message.Id.t) ~(message : Message.t) ~(app : App.t) = *)
(*   let status = [| `OK; `Bad_request |] in *)
(*   let i = status |> Array.length |> Random.int in *)
(*   match status.(i) with *)
(*   | `OK -> () *)
(*   | `Bad_request -> () *)
(* ;; *)
